### ISSUE TITLE
Prettier configuration

### ISSUE THREAD

**Issue by bt-s** [bt-s/dinnerplanner-html-react-master#15]
@Envl  could you try to change the following in your prettier setting:

- Double-quotes (") instaed of single-quotes (') in JSX
- No space between imports (e.g. `import {Link} from 'react-router-dom';` instead of `import { Link } from 'react-router-dom';`
- Place comma after last item in group (e.g. `this.setState({ status: 'ERROR', });` instead of `this.setState({ status: 'ERROR', });`)

I think this link explains you how you can change these settings: https://stackoverflow.com/questions/50975264/prettier-settings-for-vscode.

We could also choose different settings, but I have used the ones above throughout the whole code-base.

**Comment by Envl** [comment]
Done!
